name: main

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        coverage run -m pytest BigPythonEnergy\DictTest.py
        coverage run -m pytest BigPythonEnergy\PuzzleTest.py
        coverage xml -o coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
